### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by mohit67890** [uzillion/crypto-whale-watcher#7]
Hey, I'm getting this error 

UnhandledPromiseRejectionWarning: error: relation "mintradeworth" does not exist
UnhandledPromiseRejectionWarning: error: relation "volumefilter" does not exist

Please help me on this

**Comment by uzillion** [comment]
It's a database error. Make sure you create the database and run the migrations.

**Comment by SpiryMedia** [comment]
Hello, your bot looks good. But you should really inform us better how to do a DB import. I have an managed postgresql and your example doesn't show if it works or not with a db that has password and it keeps gives me the error above even if I do `npm start db:migrate` or `npm start install. `

**Comment by uzillion** [comment]
I understand, but it's hard to generalize the method for all platforms. I know PostgreSQL setup is a bit different in Mac OS compared to Ubuntu. As far as I remember it requires you to set a password before you can start using the service. That wasn't the case for me. So I added my default bash profile to psql as a role with superuser privileges, and then created a database via this user.

It doesn't matter how you create the database, as long as you tell the server how to connect to it. The most ideal way would be by specifying the `DATABASE_URL`  in the `.env` file.

I will look into finding a common method so that irrespective of someone's platform they should be able to create and connect to the database. In the meantime, if you are a Mac user, please share your method if you were successful in running the bot.

**Comment by uzillion** [comment]
> 
> 
> Hello, your bot looks good. But you should really inform us better how to do a DB import. I have an managed postgresql and your example doesn't show if it works or not with a db that has password and it keeps gives me the error above even if I do `npm start db:migrate` or `npm start install.`

@SpiryMedia the right commands are `npm run db:migrate` and `npm install`. Please refer to PostgreSQL documentation and Google searches for directions on creating a database for your specific platform. It would be hard for me to explain how a database should be created for all types of different platform out there.
